### ISSUE TITLE
QR no aparece en Factura Electrónica

### ISSUE THREAD

**Issue by FranFernandez1** [ctmil/l10n_ar_fe_qr#2]
Buen día,

Tengo instalados los módulos de Factura Electrónica de Moldeo Interactive para Odoo 13, ya funcionando en modo Test/Homologación. Instalé además el Módulo QR para la Factura Electrónica sin problemas. Dentro de la pestaña de AFIP de la Factura veo que se sumaron los campos de "JSON QR AFIP" y "Texto Modificado QR". Adjunto captura de ello. 

![image](https://user-images.githubusercontent.com/88726447/128891918-6c95749d-92bd-459c-99f9-be8f9f757c90.png)

Ahora bien, cuando intento imprimir la Factura Electrónica, no aparece el QR. Como soy Funcional (Junior) de Odoo no descarto que me esté faltando algún paso más bien simple, pero estoy trabado con esta cuestión y no encontré mucha información en Internet. Adjunto una captura de cómo se ve la factura.

![image](https://user-images.githubusercontent.com/88726447/128892244-b2a8eca3-cd11-433d-b933-3698b311c878.png)

Desde ya, cualquier ayuda es bienvenida. Muchas gracias!

**Comment by mariogustavoorrillo** [comment]
Intentamos reproducirlo y no tuvimos problema.
Cerramos el issue.
